package model;

import model.common.AppModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 26 15:51:38 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for ViewObj1.
     * @return ViewObj1
     */
    public ViewObjectImpl getViewObj1() {
        return (ViewObjectImpl) findViewObject("ViewObj1");
    }

    public void moduleMethod() {
        System.err.println("-------------------------------");
        System.err.println("Real method has been called ");
        System.err.println("-------------------------------");
    }
}

