package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 26 15:52:48 EST 2016
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void moduleMethod();
}

